# Generated by Django 4.1.3 on 2022-11-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='following',
            constraint=models.CheckConstraint(check=models.Q(('user_id', models.F('following_user_id')), _negated=True), name='prevent_self-following'),
        ),
    ]
